### ISSUE TITLE
This arena has no lobby

### ISSUE THREAD

**Issue by SheraGirl** [endercrest/ColorCube#63]
I made a map and lobby for my arena, I made the lobby, selected it, set the spawn point (global and normal lobby) etc. But the problem is that if I try to join after enabling it it said: Arena 5 has no lobby spawn. I don't know what went wrong...

(Sorry for bad english)

**Comment by PikachuPorkChops** [comment]
That's because you haven't set the spawn points in the arena. It shouldn't be displaying that message though...

To fix it: enter the arena and type "/cc setspawn next" to make the players' spawn. Do that command as many times as you want players in the arena.

If you have further questions, do not hesitate to ask.

**Comment by endercrest** [comment]
If this issue is still giving you an issue please comment.
