### ISSUE TITLE
Console warning after last player votes

### ISSUE THREAD

**Issue by tuckerandlexus** [endercrest/ColorCube#71]
Hi there, for some reason after the last player votes before the games starts I get this really long warning in the server console? I am using spigot 1.8.8 and ColorCube Beta 0.5 for 1.8.1 Here is the warning: http://pastebin.com/udeQTyGr  Thank you

**Comment by endercrest** [comment]
Thanks, I will be getting time this weekend to investigate.

**Comment by endercrest** [comment]
@tuckerandlexus looks like this is an error due to trying to use a version of ColorCube that is not compatible with 1.8.8. ColorCube also no longer supports 1.8.* so if you would like to continue to use colorcube it will be required that you update to anything above 1.9. This is something that I do not plan on patching since this system has been updated and replaced in V0.6.0-BETA.

Sorry. :/
